name: Build and push the latest build

on:
  push:
    branches: [ main ]
  # schedule:
  #   - cron: '0 6,18 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_push_image:
    name: Build and push Rstudio daily user list image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push staging images
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{secrets.ACR_NAME}}/rsession-daily:latest
          push: true
          secrets: |
            CS_POPULATE_SERVER=${{ secrets.CS_POPULATE_SERVER }}

