name: Build and push the latest build

on:
  push:
    branches: [ main ]
  #schedule:
  #  - cron: '0 6,18 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push staging images
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{secrets.ACR_NAME}}/rsession-testing:latest
          push: true
          secrets: |
            HTPASSWD_CSWEB_WGET=${{ secrets.HTPASSWD_CSWEB_WGET }}

